version: "3.9"

services:
  api:
    image: api
    networks:
      - api_network
    external_links:
      - mongodb

  gui:
    image: gui
    networks:
      - api_network

  mongodb:
    image: mongo:4.4.3
    networks:
      - api_network
    ports:
      - 27017:27017

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - gui
    networks:
      - api_network

networks:
  api_network: