version: "3.9" 

services:
  api:
    image: api
    networks:
      - api_network
    external_links:
      - mongodb
      - redis
    scale: 5

  dashboard:
    image: dashboard
    networks:
      - api_network

  redis:
    image: redis
    networks:
      - api_network
    ports:
      - 6379:6379

  mongodb:
    image: mongo:4.4.3
    networks:
      - api_network
    ports:
      - 27017:27017

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - dashboard
    networks:
      - api_network
  
  reddit-trending:
    image: web
    networks:
      - api_network

networks:
  api_network: