---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-config
  namespace: ac
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }

    http {
      server_tokens off;
      # IMPORTANT: mime.types are required, otherwise react app
      # won't load SVGs and CSS files in the right way
      include /etc/nginx/mime.types;

      server {
        listen 80;
        listen  [::]:80;
        server_name  ac-ks89.eu www.ac-ks89.eu;

        location / {
          root /etc/nginx/html/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }

        location /api {
          proxy_pass http://api-server-svc.ac.svc.cluster.local:80;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host            $http_host;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-gui
  namespace: ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-gui
  template:
    metadata:
      labels:
        app: ac-gui
    spec:
      containers:
      - name: ac-gui
        image: ks89/ac-gui
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        volumeMounts:
          - name: gui-config
            mountPath: /home/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: lets-encrypt-ssl-storage
            mountPath: "/etc/letsencrypt/"
          - name: nginx-conf-storage
            mountPath: "/home/nginx-conf/"
      volumes:
        - name: gui-config
          configMap:
            name: gui-config
        - name: lets-encrypt-ssl-storage
          persistentVolumeClaim:
            claimName: lets-encrypt-ssl-claim
        - name: nginx-conf-storage
          persistentVolumeClaim:
            claimName: nginx-conf-claim
---
kind: Service
apiVersion: v1
metadata:
  name: ac-gui-svc
  namespace: ac
spec:
  loadBalancerIP: <ADD_YOUR_PUBLIC_FLOATING_IP_HERE>
  type: LoadBalancer
  selector:
    app: ac-gui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https