---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-config
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }

    http {
      server_tokens off;
      # IMPORTANT: mime.types are required, otherwise react app
      # won't load SVGs and CSS files in the right way
      include /etc/nginx/mime.types;

      server {
        listen 80;
    #     listen  [::]:80;
    #     server_name  localhost;
    #     access_log /var/log/nginx/appstore.access.log;
    #     error_log /var/log/nginx/appstore.error.log;

        location / {
          root /etc/nginx/html/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
        }

    #     error_page   500 502 503 504  /50x.html;
    #
    #     location = /50x.html {
    #       root   /usr/share/nginx/html;
    #     }

        location /api {
          proxy_pass http://api-server-svc.default.svc.cluster.local:80;
    #       proxy_set_header X-Forwarded-For $remote_addr;
    #       proxy_set_header Host            $http_host;
    #       proxy_set_header X-Real-IP $remote_addr;
    #       proxy_set_header Host $host;
    #       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          # Following is necessary for Websocket support
    #       proxy_http_version 1.1;
    #       proxy_set_header Upgrade $http_upgrade;
    #       proxy_set_header Connection "upgrade";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-app
  template:
    metadata:
      labels:
        app: ac-app
    spec:
      containers:
      - name: ac-gui
        image: ks89/ac-gui
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: gui-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name: gui-config
          configMap:
            name: gui-config

