apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - <ac-gui-floating-ip_IP_ADDRESS>/24                #<----------------- add here your floating IP for the HTTP GUI
      - <ac-mosquitto-floating-ip_IP_ADDRESS>/24          #<----------------- add here your floating IP for the MQTT connection