apiVersion: v1
kind: PersistentVolume
metadata:
  name: lets-encrypt-ssl-volume
  namespace: ac
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/lets-encrypt-certs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lets-encrypt-ssl-claim
  namespace: ac
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf-volume
  namespace: ac
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/nginx-conf"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf-claim
  namespace: ac
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lets-encrypt-ssl-mqtt-volume
  namespace: ac
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/lets-encrypt-certs-mqtt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lets-encrypt-ssl-mqtt-claim
  namespace: ac
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi