{{ if .Values.gui.ssl.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-gui
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.certbot.guiRenewSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certbot
            image: {{ .Values.certbot.image }}
            imagePullPolicy: Always
            env:
            - name: CERTBOT_DOMAIN
              value: {{ .Values.domains.http }}
            volumeMounts:
            - name: lets-encrypt-ssl-storage
              mountPath: "/etc/letsencrypt/"
          volumes:
          - name: lets-encrypt-ssl-storage
            persistentVolumeClaim:
              claimName: lets-encrypt-ssl-claim
          restartPolicy: OnFailure
{{ end }}
{{ if .Values.mosquitto.ssl.enable }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-mqtt
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.certbot.mqttRenewSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certbot
            image: {{ .Values.certbot.image }}
            imagePullPolicy: Always
            env:
            - name: CERTBOT_DOMAIN
              value: {{ .Values.domains.mqtt }}
            volumeMounts:
            - name: lets-encrypt-ssl-mqtt-storage
              mountPath: "/etc/letsencrypt/"
          volumes:
          - name: lets-encrypt-ssl-mqtt-storage
            persistentVolumeClaim:
              claimName: lets-encrypt-ssl-mqtt-claim
          restartPolicy: OnFailure
{{ end }}