name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push api-server
        uses: docker/build-push-action@v2
        with:
          context: ./api-server
          file: ./api-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-api-server:latest
      -
        name: Build and push api-devices
        uses: docker/build-push-action@v2
        with:
          context: ./api-devices
          file: ./api-devices/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-api-devices:latest
      -
        name: Build and push api-gui
        uses: docker/build-push-action@v2
        with:
          context: ./api-gui
          file: ./api-gui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-gui:latest
