name: Docker Image CI

on:
  push:
    paths-ignore:
      - 'device/'
      - 'kubernetes-manifests/'
      - 'docs/'
    branches:
      - '**' # every branch
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: api-server - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api-server
          file: ./api-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-api-server:latest
      - name: api-devices - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api-devices
          file: ./api-devices/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-api-devices:latest
      - name: gui - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./react-gui
          file: ./react-gui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ac-gui:latest
